apimServiceName: seyonapimpro
namedValues:
  - name: 6639389a217d201ca08cf791
    properties: 
      displayName: Logger-Credentials--6639389a217d201ca08cf791
      value: "2804e53d-5184-4483-ac24-dd1ded3c695a"
loggers:
   - name: devappinsights
     properties:
      loggerType: applicationInsights
      description: prod application insights
      resourceId: "/subscriptions/6aa8cae0-4d1e-485f-8cc0-bba9a7bdc7fb/resourceGroups/seyonappinsights/providers/microsoft.insights/components/proappinsights"
      credentials:
        instrumentationKey: "{{Logger-Credentials--6639389a217d201ca08cf791}}"
      isBuffered: true
diagnostics:
   - name: applicationinsights
     properties:
       verbosity: Error
       loggerId: "/subscriptions/6aa8cae0-4d1e-485f-8cc0-bba9a7bdc7fb/resourceGroups/seyonapimrg/providers/Microsoft.ApiManagement/service/seyonapimpro/loggers/devappinsights"
backends:
apis:
    - name: apimanagementv1
      properties:
        serviceUrl: https://seyonapiapppro.azurewebsites.net/
